{% set name = "cad-to-openmc" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  sha256: 28c3d6ad9ecd3ec972f1bff86fb108fa4b9569775fdf580f50f7756a3d91fe8b
  url: https://github.com/openmsr/CAD_to_OpenMC/archive/refs/tags/v{{ version }}.tar.gz

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [win]
  skip: true  # [osx]
  skip: true  # [py<39]
  skip: true  # [py>311]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=61.0
    - pip
  run:
    - python
    - gmsh
    - python-gmsh
    - moab >=5.3.0
    - pyparsing
    - cadquery >=2.4.0
    - ocp >=7.7.2
    - trimesh
    - networkx

test:
  imports:
    - CAD_to_OpenMC
    - CAD_to_OpenMC.assembly
  files:
    - 7pin.step
  source_files:
    - tests
  commands:
    - pytest tests
  requires:
    - pytest

about:
  home: https://www.github.com/openmsr/CAD_to_OpenMC
  summary: Package to automagically convert step-geometries to h5m descriptions for neutronics by OpenMC
  description: |
    CAD_to_OpenMC is a tool that converts CAD-geometries to DAGMC-geometries by means of surface meshing
    on a geometry in a step-file.
    DAGMC-geometries may be used in particles transport packages such as OpenMC.
    By default names used for parts in the CAD-geometry are used as material tags in the DAGMC-file, but this
    may be overridden.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ebknudsen
